// Inline AssemblyScript: every `as { … }` body and every %b:where{ … %} predicate in a schema is
// emitted into one generated module, compiled once with asc, and instantiated once.
//
// Shapes become record classes (no constructor, public fields), which AssemblyScript's host
// bindings copy across the wasm boundary by value. That copy is what keeps behaviours from
// sharing mutable state with the host.

const DEFAULTS = { string: '""', i32: '0', i64: '0', f64: '0', bool: 'false' };

// classFor(shapeId) names the record class of an embedded shape.
export const scalarTypeOf = (f, classFor) => (f.embedFields ? classFor(f.refShape) : f.asType);
const typeOf = (f, classFor) => (f.single ? scalarTypeOf(f, classFor) : `Array<${scalarTypeOf(f, classFor)}>`);
const initOf = (f, classFor) => (!f.single ? '[]' : f.embedFields ? `new ${classFor(f.refShape)}()` : DEFAULTS[f.asType]);

export function recordClassSource(className, fields, comment, classFor) {
  const lines = [`// ${comment}`, `class ${className} {`, '  id: string = "";'];
  for (const f of fields) lines.push(`  ${f.name}: ${typeOf(f, classFor)} = ${initOf(f, classFor)};`);
  lines.push('}');
  return lines.join('\n');
}

function bodyOf(code) {
  return /\breturn\b/.test(code) ? code.trim() : `return (${code.trim()});`;
}

// unit = { prelude, classes: [{className, fields, comment}], functions: [{exportName, comment, params: [{name, type}], returnType, code}] }
export function generateSource(unit) {
  const parts = ['// Generated by shex-behaviours. Do not edit.'];
  if (unit.prelude) parts.push('// ---- schema prelude (%b:as{ … %}) ----', unit.prelude.trim());
  for (const c of unit.classes) parts.push(recordClassSource(c.className, c.fields, c.comment, unit.classFor));
  for (const fn of unit.functions) {
    const params = fn.params.map((p) => `${p.name}: ${p.type}`).join(', ');
    parts.push(`// ${fn.comment}\nexport function ${fn.exportName}(${params}): ${fn.returnType} {\n  ${bodyOf(fn.code)}\n}`);
  }
  return parts.join('\n\n') + '\n';
}

const memoryCache = new Map();

export async function compile(source, options = {}) {
  const key = await sourceKey(source);
  if (memoryCache.has(key)) return memoryCache.get(key);

  let files = options.cacheDir ? await readDiskCache(options.cacheDir, key) : null;
  if (!files) {
    const { default: asc } = await import('assemblyscript/asc');
    const out = {};
    const { error, stderr } = await asc.main(
      ['module.ts', '--outFile', 'module.wasm', '--bindings', 'raw', '--runtime', 'incremental', '--optimizeLevel', '2', '--noColors'],
      {
        readFile: (name) => (name === 'module.ts' ? source : null),
        writeFile: (name, contents) => { out[name] = contents; },
        listFiles: () => [],
      },
    );
    if (error) {
      const numbered = source.split('\n').map((l, i) => `${String(i + 1).padStart(4)}  ${l}`).join('\n');
      throw new Error(`AssemblyScript compilation failed:\n${stderr.toString()}\n--- generated module.ts ---\n${numbered}`);
    }
    files = { wasm: out['module.wasm'], glue: out['module.js'] };
    if (options.cacheDir) await writeDiskCache(options.cacheDir, key, files);
  }

  const module = await WebAssembly.compile(files.wasm);
  // Purity by construction: a pure module may import nothing except the abort hook. Reading the
  // clock or a random seed shows up here as an import (env.Date.now, env.seed) and is refused.
  const foreign = WebAssembly.Module.imports(module).filter((i) => !(i.module === 'env' && i.name === 'abort'));
  if (foreign.length) {
    throw new Error(`inline AssemblyScript must be pure, but the compiled module imports: ${foreign.map((i) => `${i.module}.${i.name}`).join(', ')}`);
  }
  const glueText = typeof files.glue === 'string' ? files.glue : new TextDecoder().decode(files.glue);
  const glue = await import('data:text/javascript;charset=utf-8,' + encodeURIComponent(glueText));
  const exports = await glue.instantiate(module, { env: {} });
  const result = { exports, source, key };
  memoryCache.set(key, result);
  return result;
}

// SHA-256 through Web Crypto, which Node and browsers both provide.
async function sourceKey(source) {
  const digest = await globalThis.crypto.subtle.digest('SHA-256', new TextEncoder().encode(source));
  return [...new Uint8Array(digest)].map((b) => b.toString(16).padStart(2, '0')).join('').slice(0, 24);
}

async function readDiskCache(dir, key) {
  const fs = await import('node:fs/promises');
  try {
    const [wasm, glue] = await Promise.all([fs.readFile(`${dir}/${key}.wasm`), fs.readFile(`${dir}/${key}.js`, 'utf8')]);
    return { wasm, glue };
  } catch { return null; }
}

async function writeDiskCache(dir, key, files) {
  const fs = await import('node:fs/promises');
  await fs.mkdir(dir, { recursive: true });
  await Promise.all([fs.writeFile(`${dir}/${key}.wasm`, files.wasm), fs.writeFile(`${dir}/${key}.js`, files.glue)]);
}

// ---- value conversion at the wasm boundary (i64 <-> BigInt) -----------------------------------

const toWasmScalar = (v, asType) => (asType === 'i64' ? BigInt(v) : v);
const fromWasmScalar = (v) => (typeof v === 'bigint' && Number.isSafeInteger(Number(v)) ? Number(v) : v);

export function toWasmValue(value, field) {
  const one = (v) => (field.embedFields ? toWasmRecord(v ?? {}, field.embedFields) : toWasmScalar(v ?? defaultJs(field.asType), field.asType));
  return field.single ? one(value) : (value ?? []).map(one);
}

export function toWasmRecord(record, fields) {
  const out = { id: record.id };
  for (const f of fields) out[f.name] = toWasmValue(record[f.name], f);
  return out;
}

export function fromWasm(value) {
  if (Array.isArray(value)) return value.map(fromWasm);
  if (value && typeof value === 'object') return Object.fromEntries(Object.entries(value).map(([k, v]) => [k, fromWasm(v)]));
  return fromWasmScalar(value);
}

function defaultJs(asType) {
  return asType === 'string' ? '' : asType === 'bool' ? false : 0;
}
